title: RxKarna
description: Pentesting • CTF Writeups • Cybersecurity Notes
author: RxKarna

remote_theme: pages-themes/hacker
plugins:
  - jekyll-remote-theme

show_downloads: false

permalink: pretty

collections:
CTF_WriteUps:
  output: true
  permalink: /CTF_WriteUps/:path/
Cyber_Notes:
  output: true
  permalink: /Cyber_Notes/:path/
Blog:
  output: true
  permalink: /Blog/:path/

