title: RxKarna - Cybersecurity Researcher
description: "Pentesting • CTF Writeups • Cybersecurity Notes"
author: RxKarna

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false

collections:
  ctf:
    output: true
    permalink: /ctf/:path/
  notes:
    output: true
    permalink: /notes/:path/
  blog:
    output: true
    permalink: /blog/:path/

# IMPORTANT: prevents "plain white page" by applying the theme layout everywhere
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: ctf
    values:
      layout: default
  - scope:
      type: notes
    values:
      layout: default
  - scope:
      type: blog
    values:
      layout: default
