title: RxKarna
description: Pentesting • CTF Writeups • Cybersecurity Notes
author: RxKarna

remote_theme: pages-themes/hacker
plugins:
  - jekyll-remote-theme

show_downloads: false
permalink: pretty

collections:
  ctf:
    output: true
    permalink: /ctf/:path/
  notes:
    output: true
    permalink: /notes/:path/
  blog:
    output: true
    permalink: /blog/:path/
