title: RxKarna
description: "Pentesting • CTF Writeups • Cybersecurity Notes"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
permalink: pretty

collections:
  ctf:
    output: true
    permalink: /ctf/:path/
  notes:
    output: true
    permalink: /notes/:path/
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: ctf
    values:
      layout: default
  - scope:
      path: ""
      type: notes
    values:
      layout: default
  - scope:
      path: ""
      type: blog
    values:
      layout: default
